name: SignInfo
main: denniss17.signinfo.SignInfo
version: 0.1.0
author: Denniss17
description: Create Info Signs
softdepend: [Vault]
commands:
   signinfo:
      description: Main SignInfo command
      usage: /<command>
      permission: signinfo.signinfo
      aliases: [si]
permissions:
   signinfo.create.*:
      description: Permission to create all sign types.
      default: op
   signinfo.signinfo:
      description: Permission to use the command
      default: op
   signinfo.*:
      description: All permissions
      default: op
      children:
         signinfo.signinfo: true
         signinfo.create.*: true