name: InfoSigns
main: denniss17.infosigns.InfoSigns
version: 0.1.0
author: Denniss17
description: Create info signs
softdepend: [Vault]
commands:
   infosigns:
      description: Main InfoSigns command
      usage: /<command>
      permission: infosigns.infosigns
      aliases: [is]
permissions:
   infosigns.create.*:
      description: Permission to create all sign types.
      default: op
   infosigns.infosigns:
      description: Permission to use the command
      default: op
   infosigns.*:
      description: All permissions
      default: op
      children:
         infosigns.infosigns: true
         infosigns.create.*: true