name: SignInfo
main: denniss17.signinfo.SignInfo
version: 0.1.0
author: Denniss17
description: Create Info Signs
softdepend: [Vault]
#commands:
#   title:
#      description: Manage your title
#      usage: /<command>
#      permission: ds_title.title
permissions:
   signinfo.create.*:
      description: Permission to create all sign types.
      default: op
#      children:
#         ds_title.player: true
#   ds_title.player:
#      description: Gives access to all the player commands
#      default: true
#      children:
#        ds_title.title: true